
import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "jotai";
import axios from "axios";

export const metadata: Metadata = {
  title: "Emergensee Dashboard",
  description: "Generated by create next app",
};



// https://backend-api-auvp.onrender.com/


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  axios.defaults.baseURL = 'http://localhost:3002/'

  return (
    <html lang="en">
      <body className="antialiased">
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
