
import type { Metadata } from "next";
import "./globals.css";
import axios from "axios";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Emergensee Dashboard",
  description: "Generated by create next app",};

// Set the base URL for axios
axios.defaults.baseURL = 'https://backend-api-auvp.onrender.com/';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased" suppressHydrationWarning>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
